version: '3.4'
services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    env_file:
      - .env
    environment:
      - RAILS_ENV=staging
      - PG_DATABASE=app
      - PG_HOST=postgres
      - PG_USER=app
      - PG_PASSWORD=app
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
